[meta]
name = "Nitro Dashboard"
author = "NitroQuery"
category = "Overlay"
siteid = 102
version = "1.0.0-rc.1"
blocks = [ "Plugin_NitroDashboard" ]
# perms = "paid"

[game]
min_version = "2021-06-10"
# max_version = "2021-06-03"

[script]
imports = [ "Icons.as" ]
